---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# Usuario de GitHub - REEMPLAZA 'jCharlieTrendIt' con tu nombre de usuario de GitHub
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jCharlieTrendIt
spec:
  profile:
    displayName: Juan
    email: carlos.orta@trend-it.com.mx
  memberOf: [developers]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: developers
spec:
  type: team
  children: []
